# Generated by Django 3.1.6 on 2021-05-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('order_name', models.IntegerField()),
                ('status', models.CharField(choices=[('delivered', 'DELIVERED'), ('pending', 'PENDING')], default='pending', max_length=10)),
            ],
        ),
    ]
