# Generated by Django 3.1.6 on 2021-05-04 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_auto_20210504_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orderr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_name', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('delivered', 'DELIVERED'), ('pending', 'PENDING')], default='pending', max_length=10)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.account')),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
