# Generated by Django 3.1.6 on 2021-05-04 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_auto_20210504_1818'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orderr',
            new_name='Order',
        ),
    ]
